---
inputs:
  dev_mode: false
  exclusions:
    - "vendor"
    - "node_modules"
    - ".git"

options:
  analyze_includes: true
  debug_mode: false
  pretty_print: true
  max_file_analysis_duration: 30
  max_definitions: 3000
  max_file_size: 1000000
